language : java
jdk :
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_install:
  - chomod +x gradlew

notifications:
  email:
    -learningmind@gmail.com
